/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.arquetipo.view.telasUsuario;
import br.com.arquetipo.dao.IGenericDAO;
import br.com.arquetipo.dao.impl.EditoraDAO;
import br.com.arquetipo.dao.impl.EscritorDAO;
import br.com.arquetipo.dao.impl.LeitorDAO;
import br.com.arquetipo.model.u.Editora;
import br.com.arquetipo.model.u.Escritor;
import br.com.arquetipo.model.u.Leitor;
import br.com.arquetipo.view.ObjetoCompartilhadoView;
import br.com.arquetipo.view.telasUsuario.escritor.MinhasObras;
import br.com.arquetipo.view.telasUsuario.editora.MinhasAvaliacoes;
import br.com.arquetipo.view.telasUsuario.leitor.MinhasLeituras;
import br.com.arquetipo.view.busca.Buscar;
import br.com.arquetipo.view.credenciais.Login;
import br.com.arquetipo.view.telasUsuario.editora.MinhasAvaliacoes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author barbu
 */
public class InicialUsuario extends javax.swing.JFrame {
    
    
    ObjetoCompartilhadoView objCompartilhado = new ObjetoCompartilhadoView();
    /**
     * Creates new form InicialUsuario
     */
    public InicialUsuario() {
        initComponents();
        
       
    }
    
    public void identificaUsuario() throws SQLException, ClassNotFoundException{
        
        
        IGenericDAO Gdao = null;
        
        switch (objCompartilhado.getTipoUsuario()) {
            case "Editora":
                JbAcao.setText("Minhas Avaliações");
                Gdao = new EditoraDAO();
                break;

            case "Escritor":
                JbAcao.setText("Minhas Obras");
                Gdao = new EscritorDAO();  
                break;

            default:
                JbAcao.setText("Minhas Leituras");
                Gdao = new LeitorDAO();
                 break;
        }
        Gdao.Buscar(objCompartilhado.getId());
        JlNome.setText(objCompartilhado.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JlNome = new javax.swing.JLabel();
        JbBuscar = new javax.swing.JButton();
        JbAcao = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("Bem vindo");

        JlNome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        JlNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pena2R.png"))); // NOI18N
        JlNome.setText("NOME");

        JbBuscar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        JbBuscar.setText("Buscar");
        JbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbBuscarActionPerformed(evt);
            }
        });

        JbAcao.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        JbAcao.setText("Action");
        JbAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAcaoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbAcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(JlNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAcaoActionPerformed
        // TODO add your handling code here:
        JDialog view;
        
       
        
        switch (objCompartilhado.getTipoUsuario()) {
            case "Editora":           
                view = new MinhasAvaliacoes(this,true);               
                break;
            case "Escritor":
                view= new MinhasObras(this, true);  
                
                break;
            default:
                view = new MinhasLeituras(this,true);
                break;

        }
        
          view.setLocationRelativeTo(null);
          view.setVisible(true);
          
    }//GEN-LAST:event_JbAcaoActionPerformed

    private void JbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbBuscarActionPerformed
        // TODO add your handling code here:
        
        Buscar buscar = new Buscar(this, true);
        buscar.setLocationRelativeTo(null);
        buscar.setVisible(true);
        
        
    }//GEN-LAST:event_JbBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Login view = new Login();
        view.setVisible(true);
        view.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new InicialUsuario().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAcao;
    private javax.swing.JButton JbBuscar;
    private javax.swing.JLabel JlNome;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
