/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.arquetipo.view.credenciais;
import br.com.arquetipo.dao.IGenericDAO;
import br.com.arquetipo.dao.impl.EditoraDAO;
import br.com.arquetipo.dao.impl.EscritorDAO;
import br.com.arquetipo.dao.impl.LeitorDAO;
import br.com.arquetipo.dao.impl.UsuarioDAO;
import br.com.arquetipo.model.u.Editora;
import br.com.arquetipo.model.u.Escritor;
import br.com.arquetipo.model.u.Leitor;
import br.com.arquetipo.model.u.Usuario;
import br.com.arquetipo.view.telasUsuario.InicialUsuario;
import br.com.arquetipo.view.ObjetoCompartilhadoView;

import java.sql.SQLException;

/**
 *
 * @author barbu
 */
public class NovoCadastro extends javax.swing.JFrame {

    ObjetoCompartilhadoView obj = new ObjetoCompartilhadoView();
    /**
     * Creates new form NovoCadastro
     */
    public NovoCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtNomeUsuario = new javax.swing.JTextField();
        JpSenha = new javax.swing.JPasswordField();
        JbCadastrar = new javax.swing.JButton();
        JbVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JtNomeCompleto = new javax.swing.JTextField();
        JcTipoUsuario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome de Usuário:");

        jLabel2.setText("Senha:");

        JtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeUsuarioActionPerformed(evt);
            }
        });

        JbCadastrar.setText("Cadastrar");
        JbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    JbCadastrarActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        JbVoltar.setText("voltar");
        JbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbVoltarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Completo");

        JtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeCompletoActionPerformed(evt);
            }
        });

        JcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editora", "Escritor", "Leitor" }));
        JcTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcTipoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JbVoltar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(JbCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JtNomeUsuario)
                                .addComponent(JpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JbCadastrar)
                .addGap(18, 18, 18)
                .addComponent(JbVoltar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeUsuarioActionPerformed

    private void JbCadastrarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_JbCadastrarActionPerformed
        // TODO add your handling code here:
        
        //pega os atributos da view
        String nome = JtNomeCompleto.getText();
        String tipoUsuario = (String)JcTipoUsuario.getSelectedItem();
        String nomeDeUsuario = JtNomeUsuario.getText();
        char [] senha = JpSenha.getPassword();
        
        obj.setNome(nome);
        obj.setTipoUsuario(tipoUsuario);
        //Converte para String
        String senhaString = new String(senha);


        UsuarioDAO usuDao = new UsuarioDAO();
        IGenericDAO gDAO = null;
        Usuario usu = null;
        switch (tipoUsuario) {
            
            case "Editora":
                usu = new Editora();                
                gDAO = new EditoraDAO();
                break;
            case "Escritor":
                usu = new Escritor();
                gDAO= new EscritorDAO(); 
                break;
            default:
                usu = new Leitor();

                gDAO = new LeitorDAO();
                break;
        }
        
        
       
        
        usu.setLogin(nomeDeUsuario);
        usu.setSenha(senhaString);
        usu.setNome(nome);
        usuDao.inserir(usu);
        gDAO.inserir(usu);
        
        InicialUsuario inicialUsuario = new InicialUsuario();
        inicialUsuario.setLocationRelativeTo(null);
        inicialUsuario.setVisible(true);
        inicialUsuario.identificaUsuario();
        this.dispose();
        
        
    }//GEN-LAST:event_JbCadastrarActionPerformed

    private void JbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbVoltarActionPerformed
        // TODO add your handling code here:
        Inicial inicial = new Inicial();
        inicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbVoltarActionPerformed

    private void JcTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcTipoUsuarioActionPerformed

    private void JtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeCompletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCadastrar;
    private javax.swing.JButton JbVoltar;
    private javax.swing.JComboBox<String> JcTipoUsuario;
    private javax.swing.JPasswordField JpSenha;
    private javax.swing.JTextField JtNomeCompleto;
    private javax.swing.JTextField JtNomeUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
